/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingExpensesRouteImport } from './routes/wedding-expenses'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecycleRouteImport } from './routes/recycle'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const WeddingExpensesRoute = WeddingExpensesRouteImport.update({
  id: '/wedding-expenses',
  path: '/wedding-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecycleRoute = RecycleRouteImport.update({
  id: '/recycle',
  path: '/recycle',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/events': typeof EventsRoute
  '/items': typeof ItemsRoute
  '/members': typeof MembersRoute
  '/recycle': typeof RecycleRoute
  '/settings': typeof SettingsRoute
  '/wedding-expenses': typeof WeddingExpensesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/events': typeof EventsRoute
  '/items': typeof ItemsRoute
  '/members': typeof MembersRoute
  '/recycle': typeof RecycleRoute
  '/settings': typeof SettingsRoute
  '/wedding-expenses': typeof WeddingExpensesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/events': typeof EventsRoute
  '/items': typeof ItemsRoute
  '/members': typeof MembersRoute
  '/recycle': typeof RecycleRoute
  '/settings': typeof SettingsRoute
  '/wedding-expenses': typeof WeddingExpensesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/events'
    | '/items'
    | '/members'
    | '/recycle'
    | '/settings'
    | '/wedding-expenses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/events'
    | '/items'
    | '/members'
    | '/recycle'
    | '/settings'
    | '/wedding-expenses'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/events'
    | '/items'
    | '/members'
    | '/recycle'
    | '/settings'
    | '/wedding-expenses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  EventsRoute: typeof EventsRoute
  ItemsRoute: typeof ItemsRoute
  MembersRoute: typeof MembersRoute
  RecycleRoute: typeof RecycleRoute
  SettingsRoute: typeof SettingsRoute
  WeddingExpensesRoute: typeof WeddingExpensesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-expenses': {
      id: '/wedding-expenses'
      path: '/wedding-expenses'
      fullPath: '/wedding-expenses'
      preLoaderRoute: typeof WeddingExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycle': {
      id: '/recycle'
      path: '/recycle'
      fullPath: '/recycle'
      preLoaderRoute: typeof RecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  EventsRoute: EventsRoute,
  ItemsRoute: ItemsRoute,
  MembersRoute: MembersRoute,
  RecycleRoute: RecycleRoute,
  SettingsRoute: SettingsRoute,
  WeddingExpensesRoute: WeddingExpensesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
